function reset(source)
	spawnPlayer(source, 1475, -1680, 14)
	fadeCamera(source, true)
	setCameraTarget(source,source)
end
addEventHandler('onPlayerJoin', root, function()
	reset(source)
end)
addEventHandler('onPlayerWasted', root, function()
	setTimer(reset,100,1, source)
end)
addCommandHandler("sethp", function(playerSource,commandName, hp)
	setElementHealth(playerSource,hp)
end)